task: i2v-5B
generator_type: bidirectional
generator_name: /mnt/data/nlp/user/qiaoqian/models/Wan2.2-TI2V-5B
text_encoder_name: /mnt/data/nlp/user/qiaoqian/models/Wan2.2-TI2V-5B
vae_name: /mnt/data/nlp/user/qiaoqian/models/Wan2.2-TI2V-5B
model_kwargs:
  timestep_shift: 5.0

data_path: /mnt/data/nlp/user/qiaoqian/newproject/wan2.2_5B_fp8/raw_dataset/talkvid0918_9_16_13w.jsonl
video_root:
video_reader: auto
num_frames: 17
height: 256
width: 256
target_fps: 20
max_samples: 2
num_workers: 1

mixed_precision: true
fp8: true
gradient_checkpointing: true
seed: 1234

num_train_timestep: 1000

sharding_strategy: full
generator_fsdp_wrap_strategy: size
text_encoder_fsdp_wrap_strategy: size
text_encoder_cpu_offload: false

batch_size: 1
gradient_accumulation_steps: 1
lr: 5.0e-6
beta1: 0.0
beta2: 0.999
weight_decay: 0.0
max_grad_norm: 10.0
max_steps: 1
ema_start_step: 1000

logdir: logs/smoke_talkvid0918
log_iters: 1000
save_at_end: false
disable_wandb: true
wandb_host: WANDB_HOST
wandb_key: WANDB_KEY
wandb_entity: WANDB_ENTITY
wandb_project: WANDB_PROJECT
wandb_save_dir: ""
